name: ChatbotPart2 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore "Chatbot Part2.sln"

      - name: Check Code Formatting
        run: dotnet format --verify-no-changes "Chatbot Part2.sln" || exit 1  # Fix here

      - name: Build Project
        run: msbuild "Chatbot Part2.sln" /p:Configuration=Release
